import Layout from "../Layout/Layout";

function Contact(props){
    return(<Layout>
        <p>Contact</p>
        <p>Contact</p>
        <p>Contact</p>
        <p>Contact</p>
        <p>Contact</p>
        <p>Contact</p>
        <p>Contact</p>
        <p>Contact</p>
        <p>Contact</p>
        <p>Contact</p>
        <p>Contact</p>
        <p>Contact</p>
        <p>Contact</p>
        <p>Contact</p>
        <p>Contact</p>
        <p>Contact</p>
        <p>Contact</p>
        <p>Contact</p>
        <p>Contact</p>
        <p>Contact</p>
        <p>Contact</p>
        <p>Contact</p>
        <p>Contact</p>
        <p>Contact</p>
        <p>Contact</p>
        <p>Contact</p>
        <p>Contact</p>
        <p>Contact</p>
        <p>Contact</p>
        <p>Contact</p>
        <p>Contact</p>
        <p>Contact</p>
        <p>Contact</p>
        <p>Contact</p>
        <p>Contact</p>
        <p>Contact</p>
        <p>Contact</p>
        <p>Contact</p>
        <p>Contact</p>
        <p>Contact</p>
        <p>Contact</p>
        <p>Contact</p>
        <p>Contact</p>
        <p>Contact</p>
        <p>Contact</p>
        <p>Contact</p>
        <p>Contact</p>
        <p>Contact</p>
        <p>Contact</p>
        <p>Contact</p>
        <p>Contact</p>
        <p>Contact</p>
        <p>Contact</p>
        <p>Contact</p>
        <p>Contact</p>
        <p>Contact</p>
        <p>Contact</p>
    </Layout>);
}
export default Contact;